CREATE TABLE questions (
    id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	product_id      integer,
    body            text,
    date_written    bigint,
    asker_name      text,
    asker_email     text,
    reported        bit,
    helpful     	smallint
);

CREATE TABLE answers (
    id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	question_id     integer REFERENCES questions(id),
    body            text,
    date_written    bigint,
    answerer_name   text,
    answerer_email  text,
    reported        bit,
    helpful     	smallint
);

CREATE TABLE photos (
    id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    answer_id       integer REFERENCES answers(id),
    url             text
);


-- psql seeding commands:
-- \copy questions from '/Users/will/Downloads/drive-download-20230405T154423Z-001/questions.csv' csv header
-- \copy answers from '/Users/will/Downloads/drive-download-20230405T154423Z-001/answers.csv' csv header
-- \copy photos from '/Users/will/Downloads/drive-download-20230405T154423Z-001/answers_photos.csv' csv header


--OLD: ATTEMPT AT USING TABLE INHERITANCE
--ERROR:  there is no unique constraint matching given keys for referenced table "questions" (implied answers as well)
--SQL state: 42830

-- CREATE TABLE messages (
--     id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     body            text,
--     date            date,
--     user_name       text,
--     user_email      text,
--     reported        bit,
--     helpful     smallint
-- );

-- CREATE TABLE questions (
--     product_id      integer
-- ) INHERITS (messages);

-- CREATE TABLE answers (
--     question_id     integer REFERENCES questions(id)
-- ) INHERITS (messages);

-- CREATE TABLE photos (
--     id              integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--     answer_id       integer REFERENCES answers(id),
--     url             text
-- );


-- indexing idea- save for soon
-- CREATE INDEX products_id_idx ON products (id);